### ISSUE TITLE
Compilation error in the 68000\hb68k08 project

### ISSUE THREAD

**Issue by djipi** [hth313/Calypsi-remote-debug#2]
Tested with Calypsi 5.6

C:\Projects\Calypsi\Calypsi-remote-debug\68000\hb68k08>make
as68k -DHB68K08 --data-model=far-only --code-model=small --list-file=obj/low_level_68000.lst -o obj/low_level_68000.o ../../src/low_level_68000.s
cc68k -DHB68K08 --data-model=far-only --code-model=small --list-file=obj/agent.lst -o obj/agent.o ../../src/agent.c
cc68k -DHB68K08 --data-model=far-only --code-model=small --list-file=obj/ts68hc901.lst -o obj/ts68hc901.o ../../src/ts68hc901.c
internal error: unable to label
Terminating due to errors
make: *** [Makefile:16: obj/ts68hc901.o] Error 1

**Comment by hth313** [comment]
Can you provide some example file or project so that I can reproduce it?

**Comment by djipi** [comment]
I'm using the project included in the repository. Project is located at 68000\hb68k08
I have not modified the project or the source code.

**Comment by hth313** [comment]
I have fixed it for the coming 5.7 release.
